create table if not exists public.telegram_sources (
  id bigint generated by default as identity primary key,
  channel_ref text not null unique,
  display_name text null,
  enabled boolean not null default true,
  priority integer not null default 100,
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_telegram_sources_enabled_priority
  on public.telegram_sources(enabled, priority, channel_ref);

create or replace function public.set_telegram_sources_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_telegram_sources_updated_at on public.telegram_sources;

create trigger trg_telegram_sources_updated_at
before update on public.telegram_sources
for each row
execute function public.set_telegram_sources_updated_at();

alter table public.telegram_sources enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'telegram_sources'
      and policyname = 'service_role_full_access_on_telegram_sources'
  ) then
    create policy service_role_full_access_on_telegram_sources
      on public.telegram_sources
      for all
      to service_role
      using (true)
      with check (true);
  end if;
end;
$$;