create table if not exists public.agent_ingestion_runs (
  id bigint generated by default as identity primary key,
  job_name text not null,
  trigger_source text not null,
  status text not null check (status in ('pending', 'running', 'succeeded', 'failed', 'partial')),
  source_count integer not null default 0,
  item_count integer not null default 0,
  error_message text null,
  metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  finished_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_agent_ingestion_runs_job_started_at
  on public.agent_ingestion_runs(job_name, started_at desc);

create index if not exists idx_agent_ingestion_runs_status_started_at
  on public.agent_ingestion_runs(status, started_at desc);

create or replace function public.set_agent_ingestion_runs_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_agent_ingestion_runs_updated_at on public.agent_ingestion_runs;

create trigger trg_agent_ingestion_runs_updated_at
before update on public.agent_ingestion_runs
for each row
execute function public.set_agent_ingestion_runs_updated_at();

alter table public.agent_ingestion_runs enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'agent_ingestion_runs'
      and policyname = 'service_role_full_access_on_agent_ingestion_runs'
  ) then
    create policy service_role_full_access_on_agent_ingestion_runs
      on public.agent_ingestion_runs
      for all
      to service_role
      using (true)
      with check (true);
  end if;
end;
$$;